namespace Kenlefeb.Api.Middleware {
    /// <summary>
    /// Class CaptureOptions.
    /// </summary>
    /// <autogeneratedoc />
    public class CaptureOptions
    {
        /// <summary>
        /// Gets or sets the request.
        /// </summary>
        /// <value>The request.</value>
        /// <autogeneratedoc />
        public RequestCaptureOptions  Request  { get; set; } = new RequestCaptureOptions { };
        /// <summary>
        /// Gets or sets the response.
        /// </summary>
        /// <value>The response.</value>
        /// <autogeneratedoc />
        public ResponseCaptureOptions Response { get; set; } = new ResponseCaptureOptions { };
    }
}