namespace Kenlefeb.Api.Middleware {
    /// <summary>
    /// Class ResponseCaptureOptions.
    /// </summary>
    /// <autogeneratedoc />
    public class ResponseCaptureOptions
    {
        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="ResponseCaptureOptions"/> is content.
        /// </summary>
        /// <value><c>true</c> if content; otherwise, <c>false</c>.</value>
        /// <autogeneratedoc />
        public bool Content { get; set; } = false;
    }
}